### ISSUE TITLE
without the https prefix, api.staging.ror.org/organizations defaults to staging.ror.org, i.e. http redirects to the website instead of the api url

### ISSUE THREAD

**Issue by eshadatta-crossref** [ror-community/ror-app#38]
If I try clicking on this: http://api.staging.ror.org/organizations, it takes me to the staging ror website page where I get a 404.

Desired behavior: http://api.staging.ror.org/organizations redirects to https://api.staging.ror.org/organizations

**Comment by richardhallett** [comment]
This looks like the ELB configured due to the fact the API is on api.staging.ror.org not just staging.ror.org

And all HTTP requests for staging.ror.org go to https://staging.org.org

So this needs to be changed in the terraform config to add an additional rule.

Looks like this on AWS: 
![image](https://user-images.githubusercontent.com/7294431/133465285-32fa789d-38bb-4808-9f1b-a292e5a7bd77.png)

And I believe terraform is here https://github.com/ror-community/new-deployment/commit/e06e81043d307a7d8bfd433940584fa3d4f173bb
